apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apply-nginx
  name: apply-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apply-nginx
  template:
    metadata:
      labels:
        app: apply-nginx
    spec:
      containers:
      - image: nginx:alpine
        name: nginx