apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-container
          image: nginx-img
          imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-app-service
spec:
  type: NodePort
  selector:
    app: nginx-app
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30005
